# This workflow will create a release
name: "Publish new release"

on:
  issues:
    types: [opened]

jobs:
  publish-new-release:
    name: "Publish a new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Close release issue
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          echo "Closing release issue ${ISSUE_NUMBER}"
          gh issue close \
            --reason "completed" \
            --comment "This issue is being closed as part of the release workflow." \
            $ISSUE_NUMBER
