# This workflow will create a release
name: "Publish new release"

on:
  issues:
    types: [opened]

jobs:
  publish-new-release:
    name: "Publish a new release"
    runs-on: ubuntu-latest
    steps:
      - name: Close release issue
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        shell: bash
        run: |
          echo "Closing release issue $ISSUE_NUMBER" >> $GITHUB_ENV
          gh issue close \
            --reason "Automated closure due to release workflow" \
            --comment "This issue is being closed as part of the release workflow." \
            $ISSUE_NUMBER
